/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioTrendsIndexRouteImport } from './routes/portfolio-trends/index'
import { Route as AssetItemsIndexRouteImport } from './routes/asset-items/index'
import { Route as AssetItemsAddRouteImport } from './routes/asset-items/add'
import { Route as AssetItemsAssetItemIdIndexRouteImport } from './routes/asset-items/$assetItemId.index'
import { Route as AssetItemsAssetItemIdEditRouteImport } from './routes/asset-items/$assetItemId.edit'
import { Route as AssetItemsAssetItemIdTransactionsAddRouteImport } from './routes/asset-items/$assetItemId.transactions.add'
import { Route as AssetItemsAssetItemIdTransactionsTransactionIdEditRouteImport } from './routes/asset-items/$assetItemId.transactions.$transactionId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioTrendsIndexRoute = PortfolioTrendsIndexRouteImport.update({
  id: '/portfolio-trends/',
  path: '/portfolio-trends/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetItemsIndexRoute = AssetItemsIndexRouteImport.update({
  id: '/asset-items/',
  path: '/asset-items/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetItemsAddRoute = AssetItemsAddRouteImport.update({
  id: '/asset-items/add',
  path: '/asset-items/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetItemsAssetItemIdIndexRoute =
  AssetItemsAssetItemIdIndexRouteImport.update({
    id: '/asset-items/$assetItemId/',
    path: '/asset-items/$assetItemId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetItemsAssetItemIdEditRoute =
  AssetItemsAssetItemIdEditRouteImport.update({
    id: '/asset-items/$assetItemId/edit',
    path: '/asset-items/$assetItemId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetItemsAssetItemIdTransactionsAddRoute =
  AssetItemsAssetItemIdTransactionsAddRouteImport.update({
    id: '/asset-items/$assetItemId/transactions/add',
    path: '/asset-items/$assetItemId/transactions/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetItemsAssetItemIdTransactionsTransactionIdEditRoute =
  AssetItemsAssetItemIdTransactionsTransactionIdEditRouteImport.update({
    id: '/asset-items/$assetItemId/transactions/$transactionId/edit',
    path: '/asset-items/$assetItemId/transactions/$transactionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset-items/add': typeof AssetItemsAddRoute
  '/asset-items/': typeof AssetItemsIndexRoute
  '/portfolio-trends/': typeof PortfolioTrendsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/asset-items/$assetItemId/edit': typeof AssetItemsAssetItemIdEditRoute
  '/asset-items/$assetItemId/': typeof AssetItemsAssetItemIdIndexRoute
  '/asset-items/$assetItemId/transactions/add': typeof AssetItemsAssetItemIdTransactionsAddRoute
  '/asset-items/$assetItemId/transactions/$transactionId/edit': typeof AssetItemsAssetItemIdTransactionsTransactionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset-items/add': typeof AssetItemsAddRoute
  '/asset-items': typeof AssetItemsIndexRoute
  '/portfolio-trends': typeof PortfolioTrendsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/asset-items/$assetItemId/edit': typeof AssetItemsAssetItemIdEditRoute
  '/asset-items/$assetItemId': typeof AssetItemsAssetItemIdIndexRoute
  '/asset-items/$assetItemId/transactions/add': typeof AssetItemsAssetItemIdTransactionsAddRoute
  '/asset-items/$assetItemId/transactions/$transactionId/edit': typeof AssetItemsAssetItemIdTransactionsTransactionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset-items/add': typeof AssetItemsAddRoute
  '/asset-items/': typeof AssetItemsIndexRoute
  '/portfolio-trends/': typeof PortfolioTrendsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/asset-items/$assetItemId/edit': typeof AssetItemsAssetItemIdEditRoute
  '/asset-items/$assetItemId/': typeof AssetItemsAssetItemIdIndexRoute
  '/asset-items/$assetItemId/transactions/add': typeof AssetItemsAssetItemIdTransactionsAddRoute
  '/asset-items/$assetItemId/transactions/$transactionId/edit': typeof AssetItemsAssetItemIdTransactionsTransactionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asset-items/add'
    | '/asset-items/'
    | '/portfolio-trends/'
    | '/portfolio/'
    | '/asset-items/$assetItemId/edit'
    | '/asset-items/$assetItemId/'
    | '/asset-items/$assetItemId/transactions/add'
    | '/asset-items/$assetItemId/transactions/$transactionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asset-items/add'
    | '/asset-items'
    | '/portfolio-trends'
    | '/portfolio'
    | '/asset-items/$assetItemId/edit'
    | '/asset-items/$assetItemId'
    | '/asset-items/$assetItemId/transactions/add'
    | '/asset-items/$assetItemId/transactions/$transactionId/edit'
  id:
    | '__root__'
    | '/'
    | '/asset-items/add'
    | '/asset-items/'
    | '/portfolio-trends/'
    | '/portfolio/'
    | '/asset-items/$assetItemId/edit'
    | '/asset-items/$assetItemId/'
    | '/asset-items/$assetItemId/transactions/add'
    | '/asset-items/$assetItemId/transactions/$transactionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetItemsAddRoute: typeof AssetItemsAddRoute
  AssetItemsIndexRoute: typeof AssetItemsIndexRoute
  PortfolioTrendsIndexRoute: typeof PortfolioTrendsIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  AssetItemsAssetItemIdEditRoute: typeof AssetItemsAssetItemIdEditRoute
  AssetItemsAssetItemIdIndexRoute: typeof AssetItemsAssetItemIdIndexRoute
  AssetItemsAssetItemIdTransactionsAddRoute: typeof AssetItemsAssetItemIdTransactionsAddRoute
  AssetItemsAssetItemIdTransactionsTransactionIdEditRoute: typeof AssetItemsAssetItemIdTransactionsTransactionIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-trends/': {
      id: '/portfolio-trends/'
      path: '/portfolio-trends'
      fullPath: '/portfolio-trends/'
      preLoaderRoute: typeof PortfolioTrendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-items/': {
      id: '/asset-items/'
      path: '/asset-items'
      fullPath: '/asset-items/'
      preLoaderRoute: typeof AssetItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-items/add': {
      id: '/asset-items/add'
      path: '/asset-items/add'
      fullPath: '/asset-items/add'
      preLoaderRoute: typeof AssetItemsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-items/$assetItemId/': {
      id: '/asset-items/$assetItemId/'
      path: '/asset-items/$assetItemId'
      fullPath: '/asset-items/$assetItemId/'
      preLoaderRoute: typeof AssetItemsAssetItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-items/$assetItemId/edit': {
      id: '/asset-items/$assetItemId/edit'
      path: '/asset-items/$assetItemId/edit'
      fullPath: '/asset-items/$assetItemId/edit'
      preLoaderRoute: typeof AssetItemsAssetItemIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-items/$assetItemId/transactions/add': {
      id: '/asset-items/$assetItemId/transactions/add'
      path: '/asset-items/$assetItemId/transactions/add'
      fullPath: '/asset-items/$assetItemId/transactions/add'
      preLoaderRoute: typeof AssetItemsAssetItemIdTransactionsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-items/$assetItemId/transactions/$transactionId/edit': {
      id: '/asset-items/$assetItemId/transactions/$transactionId/edit'
      path: '/asset-items/$assetItemId/transactions/$transactionId/edit'
      fullPath: '/asset-items/$assetItemId/transactions/$transactionId/edit'
      preLoaderRoute: typeof AssetItemsAssetItemIdTransactionsTransactionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetItemsAddRoute: AssetItemsAddRoute,
  AssetItemsIndexRoute: AssetItemsIndexRoute,
  PortfolioTrendsIndexRoute: PortfolioTrendsIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  AssetItemsAssetItemIdEditRoute: AssetItemsAssetItemIdEditRoute,
  AssetItemsAssetItemIdIndexRoute: AssetItemsAssetItemIdIndexRoute,
  AssetItemsAssetItemIdTransactionsAddRoute:
    AssetItemsAssetItemIdTransactionsAddRoute,
  AssetItemsAssetItemIdTransactionsTransactionIdEditRoute:
    AssetItemsAssetItemIdTransactionsTransactionIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
