/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioTrendsIndexRouteImport } from './routes/portfolio-trends/index'
import { Route as AssetitemsIndexRouteImport } from './routes/assetitems/index'
import { Route as AssetitemsAddRouteImport } from './routes/assetitems/add'
import { Route as AssetitemsAssetItemIdIndexRouteImport } from './routes/assetitems/$assetItemId.index'
import { Route as AssetitemsAssetItemIdTransactionsAddRouteImport } from './routes/assetitems/$assetItemId.transactions.add'
import { Route as AssetitemsAssetItemIdTransactionsTransactionIdEditRouteImport } from './routes/assetitems/$assetItemId.transactions.$transactionId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioTrendsIndexRoute = PortfolioTrendsIndexRouteImport.update({
  id: '/portfolio-trends/',
  path: '/portfolio-trends/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetitemsIndexRoute = AssetitemsIndexRouteImport.update({
  id: '/assetitems/',
  path: '/assetitems/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetitemsAddRoute = AssetitemsAddRouteImport.update({
  id: '/assetitems/add',
  path: '/assetitems/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetitemsAssetItemIdIndexRoute =
  AssetitemsAssetItemIdIndexRouteImport.update({
    id: '/assetitems/$assetItemId/',
    path: '/assetitems/$assetItemId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetitemsAssetItemIdTransactionsAddRoute =
  AssetitemsAssetItemIdTransactionsAddRouteImport.update({
    id: '/assetitems/$assetItemId/transactions/add',
    path: '/assetitems/$assetItemId/transactions/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetitemsAssetItemIdTransactionsTransactionIdEditRoute =
  AssetitemsAssetItemIdTransactionsTransactionIdEditRouteImport.update({
    id: '/assetitems/$assetItemId/transactions/$transactionId/edit',
    path: '/assetitems/$assetItemId/transactions/$transactionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assetitems/add': typeof AssetitemsAddRoute
  '/assetitems/': typeof AssetitemsIndexRoute
  '/portfolio-trends/': typeof PortfolioTrendsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/assetitems/$assetItemId/': typeof AssetitemsAssetItemIdIndexRoute
  '/assetitems/$assetItemId/transactions/add': typeof AssetitemsAssetItemIdTransactionsAddRoute
  '/assetitems/$assetItemId/transactions/$transactionId/edit': typeof AssetitemsAssetItemIdTransactionsTransactionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assetitems/add': typeof AssetitemsAddRoute
  '/assetitems': typeof AssetitemsIndexRoute
  '/portfolio-trends': typeof PortfolioTrendsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/assetitems/$assetItemId': typeof AssetitemsAssetItemIdIndexRoute
  '/assetitems/$assetItemId/transactions/add': typeof AssetitemsAssetItemIdTransactionsAddRoute
  '/assetitems/$assetItemId/transactions/$transactionId/edit': typeof AssetitemsAssetItemIdTransactionsTransactionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assetitems/add': typeof AssetitemsAddRoute
  '/assetitems/': typeof AssetitemsIndexRoute
  '/portfolio-trends/': typeof PortfolioTrendsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/assetitems/$assetItemId/': typeof AssetitemsAssetItemIdIndexRoute
  '/assetitems/$assetItemId/transactions/add': typeof AssetitemsAssetItemIdTransactionsAddRoute
  '/assetitems/$assetItemId/transactions/$transactionId/edit': typeof AssetitemsAssetItemIdTransactionsTransactionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assetitems/add'
    | '/assetitems/'
    | '/portfolio-trends/'
    | '/portfolio/'
    | '/assetitems/$assetItemId/'
    | '/assetitems/$assetItemId/transactions/add'
    | '/assetitems/$assetItemId/transactions/$transactionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assetitems/add'
    | '/assetitems'
    | '/portfolio-trends'
    | '/portfolio'
    | '/assetitems/$assetItemId'
    | '/assetitems/$assetItemId/transactions/add'
    | '/assetitems/$assetItemId/transactions/$transactionId/edit'
  id:
    | '__root__'
    | '/'
    | '/assetitems/add'
    | '/assetitems/'
    | '/portfolio-trends/'
    | '/portfolio/'
    | '/assetitems/$assetItemId/'
    | '/assetitems/$assetItemId/transactions/add'
    | '/assetitems/$assetItemId/transactions/$transactionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetitemsAddRoute: typeof AssetitemsAddRoute
  AssetitemsIndexRoute: typeof AssetitemsIndexRoute
  PortfolioTrendsIndexRoute: typeof PortfolioTrendsIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  AssetitemsAssetItemIdIndexRoute: typeof AssetitemsAssetItemIdIndexRoute
  AssetitemsAssetItemIdTransactionsAddRoute: typeof AssetitemsAssetItemIdTransactionsAddRoute
  AssetitemsAssetItemIdTransactionsTransactionIdEditRoute: typeof AssetitemsAssetItemIdTransactionsTransactionIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-trends/': {
      id: '/portfolio-trends/'
      path: '/portfolio-trends'
      fullPath: '/portfolio-trends/'
      preLoaderRoute: typeof PortfolioTrendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assetitems/': {
      id: '/assetitems/'
      path: '/assetitems'
      fullPath: '/assetitems/'
      preLoaderRoute: typeof AssetitemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assetitems/add': {
      id: '/assetitems/add'
      path: '/assetitems/add'
      fullPath: '/assetitems/add'
      preLoaderRoute: typeof AssetitemsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assetitems/$assetItemId/': {
      id: '/assetitems/$assetItemId/'
      path: '/assetitems/$assetItemId'
      fullPath: '/assetitems/$assetItemId/'
      preLoaderRoute: typeof AssetitemsAssetItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assetitems/$assetItemId/transactions/add': {
      id: '/assetitems/$assetItemId/transactions/add'
      path: '/assetitems/$assetItemId/transactions/add'
      fullPath: '/assetitems/$assetItemId/transactions/add'
      preLoaderRoute: typeof AssetitemsAssetItemIdTransactionsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assetitems/$assetItemId/transactions/$transactionId/edit': {
      id: '/assetitems/$assetItemId/transactions/$transactionId/edit'
      path: '/assetitems/$assetItemId/transactions/$transactionId/edit'
      fullPath: '/assetitems/$assetItemId/transactions/$transactionId/edit'
      preLoaderRoute: typeof AssetitemsAssetItemIdTransactionsTransactionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetitemsAddRoute: AssetitemsAddRoute,
  AssetitemsIndexRoute: AssetitemsIndexRoute,
  PortfolioTrendsIndexRoute: PortfolioTrendsIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  AssetitemsAssetItemIdIndexRoute: AssetitemsAssetItemIdIndexRoute,
  AssetitemsAssetItemIdTransactionsAddRoute:
    AssetitemsAssetItemIdTransactionsAddRoute,
  AssetitemsAssetItemIdTransactionsTransactionIdEditRoute:
    AssetitemsAssetItemIdTransactionsTransactionIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
